#!/usr/bin/env python3
"""Embed the unmodified project-owned Portsmouth faces; no installed font is needed."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
faces = {"": "Portsmouth.ttf", "_bold": "Portsmouth-Bold.ttf", "_italic": "Portsmouth-Italic.ttf", "_bolditalic": "Portsmouth-BoldItalic.ttf", "_mono": "PortsmouthMono.ttf"}
lines = ['// Generated by scripts/embed-fonts.py from assets/fonts. Do not edit.', '// clang-format off', '#include "text.hpp"', 'namespace paint {']
for suffix, name in faces.items():
    data = (ROOT / 'assets/fonts' / name).read_bytes()
    symbol = 'embedded_font' + suffix
    lines.append('const unsigned char ' + symbol + '[] = {')
    for start in range(0, len(data), 24):
        lines.append('    ' + ','.join(str(byte) for byte in data[start:start + 24]) + ',')
    lines += ['};', 'const unsigned int ' + symbol + '_size = ' + str(len(data)) + ';']
lines += ['} // namespace paint', '// clang-format on', '']
(ROOT / 'src/embedded_font.cpp').write_text('\n'.join(lines))
