#!/usr/bin/env python3
"""Embed the Paint-authored source without changing its pixels."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
data = (root / "assets/cursors/tool-sheet.png").read_bytes()
text = "// Generated by scripts/embed-cursors.py from the Paint-authored PNG.\n#pragma once\n#include <cstdint>\nnamespace paint::forms {\ninline constexpr std::uint8_t cursor_sheet_png[] = {\n"
text += "".join("    " + ", ".join(str(v) for v in data[i:i+24]) + ",\n" for i in range(0, len(data), 24))
text += "};\n}\n"
(root / "src/cursors/tool_sheet.hpp").write_text(text)
