#pragma once
#include <string_view>
namespace paint {
struct HelpTopic {
    std::string_view title, body;
    bool open = false;
};
inline constexpr std::string_view help_welcome =
    "Hello! A picture can begin with one little mark. This guide shows you where to "
    "click and how to try again. Close this book with the × at its upper left, or click the ? button at the "
    "right edge of the ribbon. "
    "F1 also hides or shows it.";
inline constexpr HelpTopic help_topics[] = {
    {"Atlas: sprite sheets, icons and cursors",
     "Open a sprite sheet and choose Rows and Columns. Filenames containing sprite, sheet, atlas, "
     "tileset, walk or idle offer this setup automatically; use Atlas > Set up grid for any other "
     "image. Margins and spacing handle padded sheets.\n\nClick a sprite in the ribbon to edit it. "
     "Alt+Left / Alt+Right steps through frames, even after returning to Home to paint. Ctrl-click several "
     "sprites to hold a sequence. Expand gallery shows the original rows and columns so a vertical "
     "sequence is easy to select. All frames restores the full sequence. Save writes the complete "
     "sheet. Each sprite is one flat canvas; no layers or animation container are created.\n\nICO "
     "and CUR open every stored size. CUR hotspots can be entered as X/Y pixels or chosen with "
     "Pick on canvas. Save preserves all entries. Save As from a picture to ICO or CUR offers "
     "standard sizes. Save to PNG or another ordinary image format exports the current icon "
     "image.\n\nSVG is rasterized on import. AVIF and macOS HEIC/HEIF also import to the canvas; "
     "Save chooses PNG, JPEG, BMP, TIFF, TGA, ICO or CUR. WebP and AVIF are import-only; GIF is not "
     "supported. Animated WebP and APNG are also rejected.\n\nWarp edges wraps brush strokes across "
     "opposite edges and repeats neighboring copies for seam inspection. Preserve transparency keeps "
     "every alpha value while repainting. Right-click another frame to overlay it at 50% without "
     "changing the current frame or exported image; Dismiss reference removes it."},
    {"1. Make your first picture",
     "Click Pencil in Home, then hold the mouse button and move it on the white paper. Let go to "
     "stop. Try Brushes for wider marks. Pick a little colored square to change your "
     "color.\n\nMade a mistake? Click the curved Undo arrow at the top. You can also hold Ctrl and "
     "press Z. On a Mac, Command+Z works too. Redo brings a change back.\n\n"
     "Click the selected ribbon tab to collapse it; click again or choose another tab to reopen. "
     "Wheel and trackpad scrolling stop when the viewport center reaches a canvas edge. "
     "File > Settings saves a scroll-distance multiplier in screen pixels, adjusted for zoom, and "
     "offers moss green, brown and tan felt plus slate, clay and ivory matte-painted surrounds. "
     "The original grey-blue surface remains the default. Transparency display can use a "
     "checkerboard or a chosen solid color without changing exported pixels.",
     true},
    {"2. Colors, brushes and patterns",
     "Primary and Alt each hold one material: Solid, No color, a brush, or a pattern. Choose a slot "
     "and then a material; selecting a brush clears its pattern and selecting a pattern clears its "
     "brush. Right-click a color or material to assign it to Alt. Color changes retain the chosen "
     "material. The color boxes preview their assignments.\n\n"
     "Both slots remain available. Alt supplies uncovered areas in Primary patterns and brushes; "
     "Alt No color leaves them transparent. Turn on Alt carries body beside Smooth lines to use "
     "Primary for a shape or path edge and Alt for its body instead. With that switch off, both "
     "parts use the same combined material. Edge and Fill switches control which parts are drawn. "
     "Drawing with the right mouse button uses Alt, including when Primary is Solid.\n\n"
     "Smooth lines switches between antialiased and crisp pixel edges. Size sets stroke width. "
     "The small Home Pencil always uses a solid one-pixel tip, independent of brush material.\n\n"
     "Materials includes calligraphy nibs, spray can, oil, crayon, marker, natural pencil, watercolor, "
     "bristles, pastel and charcoal, plus stripes, checks, woven patterns and dither densities. "
     "Crayon has a dense waxy core and a broken rim; charcoal has a compact core and a wider grainy "
     "powder edge. Grain, paper tooth and paint load adjust the surface.\n\n"
     "The Brushes arrow selects Additive, Mix, Heal, Carpet or Dithering brush. Mix paints local distortions "
     "onto existing "
     "pixels; its Tool tab offers effects, strength, scale and phase. Heal first captures a source, "
     "then paints from it with an aligned offset. Hardness 1 copies it; softer settings blend its "
     "detail with local OKLab color correction. Set source chooses another origin. Additive spray "
     "offers Fine glitter. Carpet generates a fiber texture from twelve presets. Its ten sliders control "
     "velvet-to-felt structure, fiber diameter, depth, disorder, crimp, roughness, dye, light, tilt and "
     "magnification. Hillshade relief adds surface shading; New fibers changes the seed. Accept the "
     "preview, then paint. Carpet settings reopens the generator. Dye and lighting determine the "
     "texture color. File > Settings offers the same fabric presets around the canvas. Pencil and Brushes "
     "have a configurable Stabilizer to smooth the stroke.\n\n"
     "The palette button cycles Basic, Custom and Themed. Custom has 29 saved colors and a red-slash "
     "Transparency swatch. Themed columns contain "
     "Primary, Alt and accent. Edit colors offers RGB or OKHSL picking, numeric RGB, hex and OKLab. "
     "Mosaic offers 96 outlined color cells per hue, with smaller cells toward saturation. Its custom pane "
     "remembers 29 saved colors "
     "between launches. Choose a slot, set its color and click Add to custom colors. OK applies the "
     "choice; Cancel keeps the original."},
    {"3. Fill, erase, pick and magnify",
     "The bucket fills the connected patch you click. A closed outline keeps the color inside; even a "
     "tiny gap lets it reach the outside. Undo if it went farther than you wanted. Patterns use the same "
     "region, with Primary and Alt making the design.\n\nClick the eraser icon to choose Hard or Soft "
     "from its arrow menu, or select Blur, Sharpen or Smudge. The Eraser tab keeps effect controls. "
     "Use Size to set the diameter. Custom size follows 64 px; the bottom size button also accepts 1–1024 "
     "px. "
     "Its round pink preview shows the area it will touch. Hard clears every "
     "touched pixel to transparency. Soft erases most strongly under the center and tapers toward the "
     "edge. "
     "Blur, Sharpen and Smudge work on existing pixels instead of clearing them. Undo restores changes. "
     "The hand-held eyedropper sets Primary on left-click and Alt on right-click. Hold and drag it to pan. "
     "The eyedropper defaults to Exact pixel; Small average and Representative sample a 5×5 region. "
     "Representative rejects isolated light and dark flecks. Its optional lens previews the sample.\n\n"
     "The magnifying glass shows a round 8× pixel preview centered on the pointer. Click to zoom in "
     "around that point; right-click "
     "zooms "
     "out. "
     "The bottom slider goes up to 1600%. The pencil previews the exact pixel under its tip before you "
     "click. "
     "Hover previews and zoom do not change your saved picture."},
    {"4. Lines, curves and shapes",
     "Choose a shape in the little gallery. Click once to anchor it, move the mouse to size it, then "
     "click again to place it. File > Settings > Lines and shapes also offers Click, hold, release. "
     "Materials selects their treatment; Alt carries body assigns Alt to interiors. "
     "The Edge and Fill switches turn either part off. Size sets outline thickness. Hold Ctrl while drawing "
     "a closed shape to keep the initial click at its center. Circles, stars and regular polygons grow "
     "by radius; other closed shapes grow symmetrically toward the pointer. Hold Shift for constrained lines "
     "and equal-sided shapes.\n\nChoose Bézier or Arc and place its starting line with two clicks "
     "(or drag it when the drag option is enabled). "
     "Bézier has a draggable control handle from each endpoint; Arc has one middle handle. "
     "Keep dragging the handles until the curve is right. Undo and Redo keep the controls editable. "
     "Escape or choosing another tool releases the curve and keeps the drawing. If you only placed "
     "the first point, Escape or right-click cancels it without leaving an anchor or a mark. Right-click "
     "also cancels an unfinished shape. A polygon is made "
     "by clicking corners; clicking the first corner closes it. Escape also finishes it."},
    {"5. The continuous junction path",
     "Choose Path at the right of Home. Click to place each corner; the next segment follows the "
     "pointer until you click. Blue dots mark editable junctions. Right-drag a dot to move it, "
     "including every branch sharing that junction.\n\n"
     "While extending a run, click any earlier junction to connect back and end the run. Click again to "
     "start another branch there. Right-click empty canvas to finish "
     "the current run, then click elsewhere to start a separate run. If only its first anchor exists, "
     "right-click discards that anchor and the pending line. Earlier runs remain visible "
     "when new ones overlap them. Undo and Redo preserve the editable geometry. Escape or changing "
     "tools finishes the paths and releases every node while leaving the drawing in place.\n\n"
     "Continuous path keeps each run open. Uncheck it to add a closing edge. An ordinary polygon "
     "closes when you click its first corner.\n\nPath > Swap segment offers Bézier and Arc. Choose one, "
     "click an active segment between blue junctions, and drag its controls. Right-click to return to "
     "ordinary Path editing.\n\nPath > Freehand shape lets you draw a continuous outline while holding the "
     "mouse button. Release to close and paint it with the current Edge, Fill, Primary and Alt materials."},
    {"6. Select, move, copy and paste",
     "Select draws a rectangle around part of the picture. The little arrow beneath Select also offers "
     "Free-form selection: draw a lasso around an object. A canvas selection stays active when you change "
     "tools: drawing, brushes, fill, stamps, erasing, paths and text affect only its selected pixels. "
     "Holes remain protected. Escape deselects and restores unrestricted painting. Pasted images stay "
     "floating above the canvas and do not restrict painting underneath. Return to Select or Lasso to "
     "move or transform a canvas selection. Drag inside the selected area to move it. Arrow "
     "keys pan the view. Alt plus an arrow nudges a selection one pixel; Alt+Shift moves ten pixels. Escape "
     "places it.\n\nCopy keeps the "
     "original. Cut removes it. Paste makes a new movable selection. Paste from opens an image file as a "
     "selection. Drag an image file from Finder or your file manager onto this window to paste it "
     "immediately. A larger pasted picture expands the canvas.\n\nTransparent selection skips pixels "
     "exactly equal to Alt. Crop keeps only the selected rectangle. With nothing selected, Crop first "
     "switches to Select so you can mark the area. Delete removes selected content. Ctrl+A followed by "
     "Delete clears the whole picture without a drag. "
     "Without a selection, Delete clears the canvas to Alt.\n\nTightening lasso follows the nearest "
     "connected object around the lasso center using perceptual color differences, with feathered "
     "edges and tolerance for small JPEG variations. Magic wand selects similar colors everywhere in the "
     "canvas from one click, including separate islands. Its tolerance uses the same perceptual color "
     "family. "
     "Inner-void lasso selects a connected background "
     "region inside a shape, expanding beyond the drawn loop. Ctrl adds a freeform lasso region; Alt "
     "subtracts one, regardless of lasso mode. Marching contours show every island and hole.\n\nGuide, the "
     "drafting triangle beside Path, protects artwork "
     "without entering the picture. Click its corners; click an earlier corner to connect back, or the first "
     "corner to close it. The next edge previews under the pointer. Right-click cancels that pending edge "
     "and removes a lone initial anchor; Set guide closes the retained outline. Drag its nodes or "
     "body to move it. Protect body, also controlled by the filled square, blocks the inside. "
     "Otherwise only its lines block Pencil, Brush, Fill and Stamp. Choose Guide with a selection "
     "to protect its silhouette directly. Click Guide again, or choose Unset guide in its arrow menu, "
     "to remove it. The arrow menu also offers Edit guide and Swap segment: choose Bezier or Arc, "
     "click a segment, then drag its handles. Right-click returns to ordinary guide editing. "
     "Cut with a guide and no pixel selection only unsets the guide; the picture stays intact. "
     "Selection, Path, shapes, text, "
     "cut, paste, crop, resize, reshape and changing atlas frames clear the guide."},
    {"7. The rubber stamp",
     "Choose Stamp at the right of Home. Open Stamp tools and pick one of 39 masks, including stars, arrows, "
     "hearts, callouts, curves and the original circle, pill, square and rectangle. "
     "Choose its width and height. The outline under the pointer shows what you will lift. Click once "
     "over a part of the picture to load the stamp. The original stays on the page.\n\nNow click in other "
     "places to print repeated copies, or hold and drag to scrub with the sample. R turns the stamp 15 "
     "degrees clockwise; Shift+R turns it the other "
     "way. + makes it bigger and - makes it smaller. These keys change the stamp, not the "
     "canvas.\n\nTransparent stamp preserves transparent pixels and skips pixels matching Alt. Turn "
     "it off to include that background color. The area outside the chosen mask is always transparent. "
     "Right-click or press Escape to clear the old sample and reset its rotation and scale, even while "
     "it is preparing. The next canvas click picks another. Stamp > Lift a new stamp does the same; "
     "the Stamp ribbon holds its size and angle controls. Hardness 1 keeps the exact mask; lower values "
     "feather its edge. Stamp > Add material retains the old stamp at half opacity while you capture "
     "new content, then heals that detail into the stamp. New material can fill previously transparent areas "
     "and extend its silhouette within the capture bounds. Clicking Stamp again closes its open menu."},
    {"8. Resize, rotate and the canvas",
     "Resize accepts percentages or pixel dimensions. Keep Maintain aspect ratio checked to avoid "
     "stretching. Scale artwork uses CONV* to reconstruct the image; turn it off to change only "
     "the canvas boundary. Smaller boundaries crop. Larger ones add Alt around the existing "
     "picture.\n\nThe round handle just outside a selection's upper-right corner turns it freely. "
     "Drag it around the object; hold Shift for 15-degree steps. Release to finish the rotation, "
     "then press Escape when you want to place the selection. The Selection ribbon also lets you enter any "
     "angle, "
     "with positive numbers turning clockwise. CONV prepares the original material once and reuses "
     "it while you drag. Large selections may take a moment to prepare.\n\nThe same menu keeps exact "
     "quarter turns, a half turn, and horizontal or vertical flips. With a selection, only that "
     "content changes. Without one, the whole picture rotates into an expanded canvas. "
     "The four small gold handles just outside the edge midpoints skew the selection. Top and bottom "
     "handles slide left/right; left and right handles slide up/down. The opposite edge stays fixed. "
     "The pixels and selection mask transform together. Resize also has horizontal and vertical Skew "
     "angles. Drag the square handles around a selection "
     "to resize its pixels, or the three handles on the canvas edge to change the paper boundary. "
     "Properties shows dimensions and lets you change the canvas size and JPEG quality.\n\n"
     "File > Settings > Enable canvas rotation handle enables a grip on the background outside a visible "
     "canvas corner. "
     "Drag it to turn your working view freely. Right-click it to return upright and see the original "
     "pixels. "
     "Rotation is off by default. It never changes stored pixels or adds an undo step; all tools, text and "
     "pasted content still use original canvas coordinates. Starting a view drag places floating content "
     "and clears the selection; resetting the view leaves active content intact. Zoom out if no background "
     "remains visible for the grip.\n\nThe rotated view uses CONV point synthesis after preparation. "
     "While preparing, or beyond the current one-million-pixel field limit, it displays direct pixel "
     "samples. "
     "Object transforms use point previews and pixel-area integration when committed."},
    {"9. Reshape an object like soft cloth",
     "Choose Free-form selection from the Select arrow. Draw all the way around your object. "
     "Then choose Selection > Start mesh. Paint puts a coarse mesh of blue "
     "knobs around the edge and through the inside. Smaller Mesh spacing gives you more knobs. "
     "Drag a knob to stretch the object. A red warning means that move would fold the mesh, "
     "so the last safe shape stays in place. Press Escape to finish, or Undo to restore the "
     "original object.\n\nThe first preparation can take a few seconds. You may move knobs "
     "while it prepares. Drag previews use point samples; finishing integrates destination pixel areas. A "
     "source can contain at most one million pixels. Select "
     "a smaller "
     "object or resize it first if Paint explains that it is too large."},
    {"10. Put words in your picture",
     "Click the A tool, then click the canvas. Type into the box. The Text tab lets you choose a "
     "font face, size, bold, italic, underline, "
     "strikeout, and an opaque "
     "background. Drag Move text to reposition the box and drag its edge handles to resize it. "
     "Word wrap moves whole words onto the next line; switch it off for explicit line breaks only. "
     "Color 1 colors the letters; Alt colors an opaque background. Place text "
     "stamps the words into the picture. Cancel text discards them. Undo removes placed text if "
     "you change your mind. Ctrl+Enter places text; Escape cancels it.\n\nDynaPuff, Bubble Sans, Anton and "
     "Titan One are bundled poster fonts. Outline letters draws Primary around the contours and "
     "counter edges, with Alt filling the letter body. Adjust the outline width. WordArt offers "
     "extrusion, embossing and a Primary-to-Alt gradient. Skew, Perspective and Bend transform the "
     "editable text preview; Reset restores plain geometry and treatment."},
    {"11. Open, save and print",
     "File > Open replaces the picture with an image from disk. Save writes your picture. Save as lets "
     "you choose a new name or format. PNG, TIFF and TGA can preserve transparency. JPEG is smaller for "
     "photographs but loses detail each time it is re-encoded. BMP and JPEG use a white background for "
     "transparent areas.\n\nYou can "
     "open PNG, JPEG, direct-color BMP, uncompressed RGB/RGBA TIFF, TGA, WebP, SVG, AVIF, ICO and CUR, "
     "plus HEIC/HEIF on macOS. WebP, AVIF and HEIC/HEIF are import-only. GIF and paletted BMP import are "
     "disabled because their available decoder "
     "paths are unsafe for untrusted files. SVG raster image elements are likewise disabled. Animated "
     "WebP and APNG are not supported. "
     "Saving exports flat raster artwork; ICO and CUR retain their multiple images.\n\nThe application "
     "asks before replacing "
     "unsaved work. Cancel keeps you here. Printing uses the system's print dialog where available. Keep "
     "a saved copy of pictures you care about.\n\nRecent pictures remembers your last twelve opened or "
     "saved files. From scanner or camera uses Windows Image Acquisition on Windows. On a Mac it opens "
     "Image Capture; on Linux it opens Document Scanner or XSane. In those capture applications, save "
     "the picture, then drag it into Paint or choose Paste from. A connected device and its driver "
     "are needed.\n\nSet as desktop background offers Fill "
     "(cover the screen), Tile (repeat), and Center (keep the picture's size). These commands keep "
     "their exported copies in Paint's private preferences folder so the other application can "
     "continue using them."},
    {"12. View and keyboard guide",
     "View has Zoom in, Zoom out, 100%, rulers, gridlines, the status bar, Full screen and Fit window. "
     "Pixel gridlines appear at 400% zoom and above. Ctrl or Command plus the mouse wheel changes zoom. "
     "Arrow keys pan; Shift pans farther. Alt+arrows nudge selections or navigate atlas frames. "
     "F11 toggles full screen.\n\nCtrl / Command shortcuts:\nN: New    O: Open    S: Save\nShift+S or "
     "F12: Save as\nZ: Undo    Y or Shift+Z: Redo\nX: Cut    C: Copy    V: Paste\nA: Select all    P: "
     "Print\nE: Properties    W: Resize    I: Invert colors\nG: Gridlines\n\nEscape places a selection or "
     "releases a path, clears a loaded stamp, or cancels text. F1 opens this guide. R and +/- change "
     "a loaded stamp."},
    {"13. How I made this - Astra",
     "Plan Paint uses native GUI.Forms controls and CPU rendering. The older SDL/ImGui frontend is "
     "deprecated and is not included in releases. The application is written in C++, using "
     "explicit types, "
     "named operations and callbacks, clear ownership, and inspectable "
     "numerical loops. I chose the Windows 7/10 Paint ribbon as the visual and behavioral reference.\n\nI "
     "keep the document as a contiguous RGBA image. Editing gestures create undo checkpoints, and a "
     "floating selection owns its pixels until it is placed. Flood fill finds the region before painting "
     "it, so patterned fills can safely reuse the original colors.\n\nFor scaling, I ported the website "
     "CONV* demonstrator to native C++ using double precision, precomputed sampling plans and reusable "
     "worker storage. Changed dimensions integrate the reconstruction over full destination-pixel basins. "
     "Unchanged dimensions retain their exact samples. Alpha is premultiplied during resampling to avoid "
     "colored fringes. "
     "Lines shorter than five pixels use an explicit short-line interpolation rule because the five-point "
     "stencil does not exist there.\n\nFor free deformation I compiled the paper's joint CONV field "
     "into a shared quintic control atlas, then built a coarse triangle mesh for the geometry. "
     "The compact beta-star "
     "variant supplies the material. Color is constrained to the available opacity before averaging. "
     "Final affine and mesh transforms clip target pixel footprints at source cells and integrate each part. "
     "Preparation "
     "runs on a background worker, and dragging reuses the compiled material.\n\nI use stb and libtiff "
     "for file encoding and decoding, and libwebp for decoding. GUI.Forms and the image libraries retain "
     "their own permissive license notices. This is "
     "an independent implementation; it does not contain Microsoft's Paint code or artwork."},
    {"14. Free for everyone",
     "To the Holy One, blessed be He, from whom all good things come. This work is dedicated in "
     "gratitude for the nourishment that sustains human life, the energy that powers our tools, "
     "and the opportunity to weave information into works of use and beauty.\n\n"
     "Author: Astra\nSponsor: Rainstar\nCopyright (c) 2026 "
     "joshuah.rainstar@gmail.com\n\nPlan Paint is free and open source under the MIT license. Anyone "
     "may use it, learn from it, change it, and share it, including for commercial work. Keep the "
     "copyright and license notice with copies. The license does not promise a warranty.\n\nYour pictures "
     "are yours. There is no account, subscription, advertising, or upload service in the drawing "
     "workflow. The complete source and dependency notices are supplied with the project."},
    {"Gradient fills",
     "Open the arrow on the Fill bucket and choose Use gradient. The Gradients ribbon offers twelve "
     "presets, including Rainbow spectrum, Sunset fire, Electric blue, Metallic chrome, Gunmetal and "
     "Purple galaxy. Linear follows the chosen angle: 0 degrees goes left to right; 90 goes top to bottom. "
     "Circular radiates from the center of the connected region.\n\n"
     "Click the color strip to add a stop, then drag its handle. Stop and Position provide precise "
     "selection and placement. Color opens the stop's color and alpha editor without changing Primary "
     "or Alt. Add, Remove and Reverse edit the progression; keep between 2 and 32 stops.\n\n"
     "Click the canvas to fill. Selections, their holes and guides constrain the connected area. Each "
     "fill undoes once. Editing stops affects the next fill; Undo and fill again to revise a painted "
     "gradient. Settings last for this session. Solid / material fill restores the ordinary bucket."},
    {"Spirograph guides, inserts and pegs",
     "Open the Path arrow and choose Spirograph. Its ribbon has separate guide and insert catalogs. "
     "Start with the ring and wheel, then explore shaped guides, racks and other compatible inserts. "
     "The translucent apparatus is a temporary guide; it does not become part of the saved picture.\n\n"
     "Drag a peg from the ribbon into an insert hole. Use Fill to load the peg with ink. Click a peg "
     "to select it, then choose its brush medium in Materials or the peg medium menu. Its top previews "
     "the effect. Gel pen gives a solid line with subtle variation and small glints. Drag the insert's "
     "center to operate it; loaded pegs draw as it follows the guide.\n\n"
     "Move the support by dragging its body; the red close button removes it. Removing an insert clears "
     "its pegs. Tools that dismiss an ordinary guide also dismiss the spirograph, keeping its drawn lines."},
    {"Your own pattern canvas",
     "Materials includes a custom tile alongside the pattern gallery. Choose Edit custom pattern "
     "to open its separate canvas. Left draws black; right draws white. The repeating preview shows "
     "the material mask. Set width and height from 1 to 128 pixels.\n\n"
     "The tile has independent Undo and Redo and is saved for the next launch. Return to main canvas "
     "restores the picture, view, selection and history. Primary and Alt supply its colors when painting."},
    {"Interface settings, saving and recovery",
     "File > Settings offers an interface hue, including blue, pink, purple and green. Its preview "
     "changes the controls without recoloring your picture, icons or golden selected tools. Cancel "
     "restores the previous appearance.\n\n"
     "Save replaces a completed file atomically. Crash recovery is on by default, with a 60-second "
     "interval; Settings accepts 15 to 600 seconds. Snapshots wait for active gestures and transforms. "
     "They preserve a flattened picture, not editable text, guides, selections or undo history.\n\n"
     "An empty launch offers recoverable artwork. File > Recover unfinished artwork opens the same "
     "browser. Yes opens an unsaved recovered copy, No keeps that snapshot for later, and Cancel stops "
     "browsing. Save the recovered copy to an explicit destination. Recovery never overwrites the "
     "original file. Existing Rainstar Paint preferences and recovery records remain available in Plan "
     "Paint."},
    {"The name Plan Paint",
     "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, "
     "plans to give you hope and a future.\n\nJeremiah 29:11\n\n"
     "Plan Paint is the name of the application from version 1.0. Earlier releases were called Rainstar "
     "Paint."},
    {"Dithering and posterizing",
     "Select an area, open the Selection arrow, and choose Dither / posterize. Choose 2-32 colors "
     "and Crosswind, Weave, Scrambled, Drift, or Posterize. The preview prepares the exact result. "
     "OK applies it in one Undo step; Cancel keeps the original. With no canvas selection, the "
     "whole canvas is processed. Alpha and selection holes are preserved.\n\n"
     "For local changes, open the Brushes arrow and choose Dithering brush. Its spray is denser "
     "near the center. Normally, sampled pixels move halfway toward their neighborhood average. "
     "Enable Brightness / saturation noise in the Tool ribbon for small color variations instead. "
     "Both modes use existing artwork, preserve alpha, and respect the active selection."},
    {"Language and accessible drawing", "Choose Settings > Canvas controls to draw without holding a pointer button. Enter Canvas X and Canvas Y in original image pixels, then choose Move to position. Primary click and Alt click perform one click. Start stroke, movement buttons, and Finish stroke draw a continuous mark; Step (pixels) controls each movement. Constrain shape and Draw from center replace held modifiers. With the canvas focused, arrow keys move the drawing position and Space clicks. Undo removes the last completed mark.\n\nActivate a peg size with the keyboard or an accessibility action to place a peg in the selected socket, or the first empty socket. Fill pegs loads ink. On the pattern canvas, arrow keys choose a pixel, Space paints black, and Enter paints white.\n\nChoose Language in Settings and restart Plan Paint to apply it. Use system language follows the operating system preference list. English is built into the application and remains available when a translation file is missing. Translation files live in the languages folder."},
};
} // namespace paint
